### PR TITLE
Workers

### PR DESCRIPTION
**Pull request by koeninger**

### CODE REVIEW

**Comment by lgrignon** [comment]
Hello @koeninger, thanks for contributing! Did you close this PR by mistake?

**Comment by lgrignon** [comment]
This example seems nice but would be more appropriate in a dedicated repository, don't you think? Maybe that's why this PR  was eventually closed ? :)

**Comment by koeninger** [comment]
Sorry, I made that PR by mistake, which is why I closed it.

While I'm already bothering you, do you happen to know if there's a better
source of java typings for the Fetch api?  The candy i was using seemed to
result in duplicate d.ts definitions, which is why I was running tsc
separately.

**Comment by lgrignon** [comment]
Hello. Sorry I didn't answer earlier. 
Java typings (jsweet-core/es5&6) are fully open source, please feel free to modify it to better match the actual API and file a PR, I will review ASAP and deploy again.

**Pull request closed without merging**
